// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrinterManagementAppLibrary.DataAccess.SQL;

#nullable disable

namespace PrinterManagementAppLibrary.Migrations
{
    [DbContext(typeof(SQLDBContext))]
    [Migration("20230414065045_seeddata2")]
    partial class seeddata2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PrinterManagementAppLibrary.Models.PrinterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("MachineNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Site")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Printers");

                    b.HasData(
                        new
                        {
                            Id = 199,
                            Department = "Parts SWT",
                            IP = "172.16.1.117",
                            Location = "SWT Parts Manager (Andrew)",
                            MachineNo = "31258",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STPMAN",
                            SerialNo = "CNMRPCL5J8",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 190,
                            Department = "Service SWT",
                            IP = "172.16.1.118",
                            Location = "SWT Warranty Clerk (Sharina)",
                            MachineNo = "31451",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STPWAR",
                            SerialNo = "CNMKM7P2KF",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 192,
                            Department = "Admin  SWT",
                            IP = "172.16.1.119",
                            Location = "	Accounts Pay Mazda (Heidi)",
                            MachineNo = "31450",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STADMIN2",
                            SerialNo = "CNMKM6RB3W",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Admin",
                            IP = "172.16.1.120",
                            Location = "SWT Accounts Pay (Sarah)",
                            MachineNo = "31447",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "ACCPAY",
                            SerialNo = "CNMKM6R9ZV",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Admin",
                            IP = "172.16.1.121",
                            Location = "SWT Accounts Rec (Lorraine)",
                            MachineNo = "31469",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "ACCREC",
                            SerialNo = "CNMRPCL540",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 5,
                            Department = "New Cars SWT",
                            IP = "172.16.1.122",
                            Location = "SWT Admin Clerk 1 (Jiki)",
                            MachineNo = "31466",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STVEHPRO",
                            SerialNo = "CNMRPCL5JT",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 6,
                            Department = "New Cars SWT",
                            IP = "172.16.1.123",
                            Location = "SWT Vehicle Processing (Nick)",
                            MachineNo = "31463",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STFLEET2",
                            SerialNo = "CNMRPCL5K4",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 7,
                            Department = "New Cars SWT",
                            IP = "172.16.1.124",
                            Location = "SWT Fleet Manager (Ben)",
                            MachineNo = "31464",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STFMAN",
                            SerialNo = "CNMRPCL5KN",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 8,
                            Department = "New Cars SWT",
                            IP = "172.16.1.125",
                            Location = "SWT Stock Control 2 (Rebecca)",
                            MachineNo = "31468",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STSTOCK2",
                            SerialNo = "CNMRPCL5L1",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 9,
                            Department = "Admin",
                            IP = "172.16.1.127",
                            Location = "HR Manager (Kathy)",
                            MachineNo = "31465",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "HRMAN",
                            SerialNo = "CNMRPCL5M1",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 10,
                            Department = "Admin",
                            IP = "172.16.1.128",
                            Location = "SWT Admin Manager (Fiona)",
                            MachineNo = "31467",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STOM",
                            SerialNo = "CNMRPCL5MM",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 11,
                            Department = "Admin",
                            IP = "172.16.1.129",
                            Location = "SWT Group Financial Controller (Greig)",
                            MachineNo = "31457",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "STACC2",
                            SerialNo = "JPBRP8F323",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 12,
                            Department = "Used Cars SWT",
                            IP = "172.16.1.130",
                            Location = "SWT Used Cars Manager (Steve)",
                            MachineNo = "31460",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "STUSEDCOLOUR",
                            SerialNo = "JPBRP8F329",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 13,
                            Department = "Service SWT",
                            IP = "172.16.1.134",
                            Location = "SWT Admin (Scanner)",
                            MachineNo = "???",
                            Manufacturer = "HP",
                            Model = "8500FN2",
                            Name = "STSCANNER",
                            SerialNo = "CN7B713024",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 14,
                            Department = "Admin Mazda",
                            IP = "172.16.1.137",
                            Location = "SWM Office Clerk (Cassie)",
                            MachineNo = "31470",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SMOFFMAN",
                            SerialNo = "CNMRPCL5N5",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 15,
                            Department = "Service SWT",
                            IP = "172.16.1.138",
                            Location = "SWT Fleet BM (Kristy)",
                            MachineNo = "31486",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STFLEETBM",
                            SerialNo = "CNMRPCL4SN",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 16,
                            Department = "Fleet SWT",
                            IP = "172.16.1.140",
                            Location = "SWT Fleet Manager (Daniel)",
                            MachineNo = "31483",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STFLEET3",
                            SerialNo = "CNMRPCL4T6",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 17,
                            Department = "Admin",
                            IP = "172.16.1.141",
                            Location = "SWT Payroll (Sarah)",
                            MachineNo = "31484",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SWPAY",
                            SerialNo = "CNMRPCL5Y5",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 18,
                            Department = "Service SWT",
                            IP = "172.16.1.142",
                            Location = "SWT Service (Sumeshan)",
                            MachineNo = "31485",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STSAM",
                            SerialNo = "CNMRPCL6CM",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 19,
                            Department = "Finance SWT",
                            IP = "172.16.1.143",
                            Location = "ST Reception 2",
                            MachineNo = "31636",
                            Manufacturer = "Oki",
                            Model = "E77822",
                            Name = "STRECEPTION2",
                            SerialNo = "CND1N64020",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 20,
                            Department = "Admin  SWT",
                            IP = "172.16.1.144",
                            Location = "SWT Admin (1st Floor)",
                            MachineNo = "22938",
                            Manufacturer = "HP",
                            Model = "E77830",
                            Name = "STACOPIER",
                            SerialNo = "CNB8K7R26G",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 21,
                            Department = "Used Cars SWT",
                            IP = "172.16.1.145",
                            Location = "SWT Used Cars Service (Mark)",
                            MachineNo = "31482",
                            Manufacturer = "HP",
                            Model = "E60155",
                            Name = "STUTECH",
                            SerialNo = "CNMRPCL6DJ",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 22,
                            Department = "Used Cars SWT",
                            IP = "172.16.1.146",
                            Location = "SWT Used Cars (Billy)",
                            MachineNo = "31496",
                            Manufacturer = "HP",
                            Model = "E60155",
                            Name = "STWSALE",
                            SerialNo = "CNMRPCL6B7",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 23,
                            Department = "Admin  SWT",
                            IP = "172.16.1.147",
                            Location = "IT Dept (Craig)",
                            MachineNo = "31487",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "IT",
                            SerialNo = "CNMRPCL6C8",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 24,
                            Department = "Admin  SWT",
                            IP = "172.16.1.148",
                            Location = "IT Dept (Craig)",
                            MachineNo = "31422",
                            Manufacturer = "HP",
                            Model = "E78325",
                            Name = "ITCOPIER",
                            SerialNo = "CNB1P3Q1CQ",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 25,
                            Department = "New Cars SWT",
                            IP = "172.16.1.149",
                            Location = "SWT New Cars",
                            MachineNo = "22936",
                            Manufacturer = "HP",
                            Model = "E77830",
                            Name = "STRECEPTION",
                            SerialNo = "CNB8K7R26M",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 26,
                            Department = "Admin",
                            IP = "172.16.1.150",
                            Location = "SWT Group CFO (Richard)",
                            MachineNo = "31461",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "FINCON",
                            SerialNo = "JPBRP8F33W",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 27,
                            Department = "Finance SWT",
                            IP = "172.16.1.151",
                            Location = "SWT Finance Business Manager 2 (Jillian)",
                            MachineNo = "22939",
                            Manufacturer = "HP",
                            Model = "E77830",
                            Name = "STBM2COPIER",
                            SerialNo = "CNB8K7R26W",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 28,
                            Department = "Parts SWT",
                            IP = "172.16.1.152",
                            Location = "SWT Parts Warehouse",
                            MachineNo = "31640",
                            Manufacturer = "Oki",
                            Model = "E87650",
                            Name = "STPCOPIER",
                            SerialNo = "CNB8K2S0LB",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 29,
                            Department = "Service SWT",
                            IP = "172.16.1.153",
                            Location = "SWT Service (David)",
                            MachineNo = "31637",
                            Manufacturer = "HP",
                            Model = "E77822",
                            Name = "STSCOPIER",
                            SerialNo = "CND1N64023",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 30,
                            Department = "Used Cars SWT",
                            IP = "172.16.1.154",
                            Location = "SWT Used Cars (Steve)",
                            MachineNo = "31638",
                            Manufacturer = "Oki",
                            Model = "E77822",
                            Name = "STUSEDCOPIER",
                            SerialNo = "CND1N6702Q",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 31,
                            Department = "Finance SWT",
                            IP = "172.16.1.155",
                            Location = "SWT Finance Business Manager 1 (Sarah)",
                            MachineNo = "31629",
                            Manufacturer = "Oki",
                            Model = "E78330",
                            Name = "STBM1COPIER",
                            SerialNo = "CNB1P960G1",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 32,
                            Department = "Admin  SWT",
                            IP = "172.16.1.156",
                            Location = "SWT Fixed Operation Office (David)",
                            MachineNo = "31631",
                            Manufacturer = "Oki",
                            Model = "E78330",
                            Name = "STFXDOPCOPIER",
                            SerialNo = "CNB1P960G2",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 33,
                            Department = "Fleet  SWT",
                            IP = "172.16.1.157",
                            Location = "SWT Fleet 1 (Chris)",
                            MachineNo = "31497",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STFLEET",
                            SerialNo = "CNMRPCL68G",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 34,
                            Department = "Admin",
                            IP = "172.16.1.159",
                            Location = "SWT Accountant (Vineel)",
                            MachineNo = "31458",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "STACC3",
                            SerialNo = "JPBRP8F31N",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 35,
                            Department = "Service SWT",
                            IP = "172.16.1.160",
                            Location = "SWT Service R/Orders (Craig)",
                            MachineNo = "31500",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STSRO",
                            SerialNo = "CNMRPCL699",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 36,
                            Department = "Parts SWT",
                            IP = "172.16.1.161",
                            Location = "SWT Parts Warehouse (Middle)",
                            MachineNo = "31501",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STPARTS",
                            SerialNo = "CNMRPCL68P",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 37,
                            Department = "Service SWT",
                            IP = "172.16.1.162",
                            Location = "SWT Service Invoice (Kiara)",
                            MachineNo = "31499",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STSINV",
                            SerialNo = "CNMRPCL624",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 38,
                            Department = "New Cars SWT",
                            IP = "172.16.1.163",
                            Location = "SWT New Cars",
                            MachineNo = "31498",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STNEW",
                            SerialNo = "CNMRPCL6D4",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 39,
                            Department = "Parts SWT",
                            IP = "172.16.1.164",
                            Location = "SWT Parts Ph Room (Brandon)",
                            MachineNo = "31503",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STPINV",
                            SerialNo = "CNMRPCL67F",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 40,
                            Department = "Used Cars SWT",
                            IP = "172.16.1.165",
                            Location = "SWT Used Cars (Jason)",
                            MachineNo = "31502",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STUSED",
                            SerialNo = "CNMRPCL6BJ",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 41,
                            Department = "Admin",
                            IP = "172.16.1.166",
                            Location = "Payroll Copier (Sarah)",
                            MachineNo = "31420",
                            Manufacturer = "HP",
                            Model = "E78325",
                            Name = "PAYCOPYA3",
                            SerialNo = "CNB1P3Q1DB",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 42,
                            Department = "Sales SWT",
                            IP = "172.16.1.167",
                            Location = "SWT Aftermarket (Trish)",
                            MachineNo = "31530",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SWAFTM",
                            SerialNo = "CNMRPCL754",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 43,
                            Department = "CL New Cars(Admin)",
                            IP = "172.16.1.168",
                            Location = "SWT Admin Clerk 2(Belinda)",
                            MachineNo = "31529",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STADMIN",
                            SerialNo = "CNMRPCL75C",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 44,
                            Department = "Parts SWT",
                            IP = "172.16.1.179",
                            Location = "SW Picking Slip (Daniel)",
                            MachineNo = "####",
                            Manufacturer = "Kyocera",
                            Model = "P3045DN",
                            Name = "SWPICK",
                            SerialNo = "VM59206607",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 45,
                            Department = "Parts SWT",
                            IP = "172.16.1.210",
                            Location = "SWT Parts Warehouse (Middle)",
                            MachineNo = "####",
                            Manufacturer = "Zebra",
                            Model = "ZT410",
                            Name = "####",
                            SerialNo = "18J155301053",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 46,
                            Department = "Parts SWT",
                            IP = "172.16.1.211",
                            Location = "SWT Parts Warehouse (Daniel)",
                            MachineNo = "####",
                            Manufacturer = "Zebra",
                            Model = "ZT410",
                            Name = "####",
                            SerialNo = "18J170405949",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 47,
                            Department = "Service SWT",
                            IP = "172.16.1.150",
                            Location = "SWT Service (Gayle)",
                            MachineNo = "31506",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STSADM1",
                            SerialNo = "CNMRPCL75N",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 48,
                            Department = "New Car SWT",
                            IP = "172.16.1.151",
                            Location = "SWT Business Manager (Rod)",
                            MachineNo = "31445",
                            Manufacturer = "HP",
                            Model = "E52645",
                            Name = "STFIMAN",
                            SerialNo = "####",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 49,
                            Department = "Admin SWT",
                            IP = "172.16.1.152",
                            Location = "Director PA (Mandie)",
                            MachineNo = "31543",
                            Manufacturer = "HP",
                            Model = "E57540",
                            Name = "STGOPA",
                            SerialNo = "CNBRPCJ4XP",
                            Site = "GoldCoast"
                        },
                        new
                        {
                            Id = 50,
                            Department = "SM New Cars",
                            IP = "172.16.2.149",
                            Location = "SM Business Manager (Chris)",
                            MachineNo = "31424",
                            Manufacturer = "HP",
                            Model = "E78325",
                            Name = "SMBM1",
                            SerialNo = "CNB1P3Q1DJ",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 51,
                            Department = "SM New Cars",
                            IP = "172.16.2.150",
                            Location = "SM Fleet (Loona)",
                            MachineNo = "31432",
                            Manufacturer = "HP",
                            Model = "E77825",
                            Name = "SMFLEET",
                            SerialNo = "CNB8K3A0F3",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 52,
                            Department = "SM New Cars",
                            IP = "172.16.2.151",
                            Location = "SM New Cars (Reception)",
                            MachineNo = "22935",
                            Manufacturer = "HP",
                            Model = "E77830",
                            Name = "SMRECEPTION",
                            SerialNo = "CNB8K831L1",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 53,
                            Department = "SM New Cars",
                            IP = "172.16.2.152",
                            Location = "SM Business Manager (Amanda)",
                            MachineNo = "22933",
                            Manufacturer = "HP",
                            Model = "E77822",
                            Name = "SMBM2",
                            SerialNo = "CNB8K831KY",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 54,
                            Department = "SM New Cars",
                            IP = "172.16.2.153",
                            Location = "SM Marketing Manager (Amanda",
                            MachineNo = "31462",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "SMMARKET",
                            SerialNo = "####",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 55,
                            Department = "SM New Cars",
                            IP = "172.16.2.154",
                            Location = "SM Sales Manager (Jason)",
                            MachineNo = "31456",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "SMSALEMAN",
                            SerialNo = "JPBRP8F338",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 56,
                            Department = "SM New Cars",
                            IP = "172.16.2.155",
                            Location = "SM Stock Control (Jade)",
                            MachineNo = "31444",
                            Manufacturer = "HP",
                            Model = "E60155",
                            Name = "SMSCON",
                            SerialNo = "####",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 57,
                            Department = "SM New Cars",
                            IP = "172.16.2.156",
                            Location = "SM Aftermarket (Lucinda)",
                            MachineNo = "31481",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SWMAFT",
                            SerialNo = "####",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 58,
                            Department = "SM Used Cars",
                            IP = "172.16.2.158",
                            Location = "SM Used Cars Tech (Wesley)",
                            MachineNo = "31452",
                            Manufacturer = "HP",
                            Model = "E60155",
                            Name = "SMUTECH",
                            SerialNo = "CNMKM6RB28",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 59,
                            Department = "SM Used Cars",
                            IP = "172.16.2.159",
                            Location = "SM Used Cars",
                            MachineNo = "31639",
                            Manufacturer = "Oki",
                            Model = "ES8473",
                            Name = "SMUCOPIER",
                            SerialNo = "CNB8K2S0M2",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 60,
                            Department = "SM New Cars",
                            IP = "172.16.2.160",
                            Location = "SM Dealer Principle (Cleve)",
                            MachineNo = "31542",
                            Manufacturer = "HP",
                            Model = "E57540",
                            Name = "SMDP",
                            SerialNo = "CNBRPCJ4TX",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 61,
                            Department = "SM New Cars",
                            IP = "172.16.2.161",
                            Location = "SM CRM Copier (Amanda)",
                            MachineNo = "31446",
                            Manufacturer = "HP",
                            Model = "E52645",
                            Name = "SMCRMCOPIER",
                            SerialNo = "CNCRNDXB4Z",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 62,
                            Department = "SM New Cars",
                            IP = "172.16.2.165",
                            Location = "SM Business Manager (Matthew)",
                            MachineNo = "31634",
                            Manufacturer = "HP",
                            Model = "E77822",
                            Name = "SMBM3",
                            SerialNo = "CND1N6702V",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 63,
                            Department = "SM Used Cars",
                            IP = "172.16.2.168",
                            Location = "SM Used Cars",
                            MachineNo = "31527",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SMUSED",
                            SerialNo = "CNMRPCL5HR",
                            Site = "SpringwoodMazdaSales"
                        },
                        new
                        {
                            Id = 64,
                            Department = "Parts SM",
                            IP = "172.16.6.161",
                            Location = "SM Parts (Rob)",
                            MachineNo = "31515",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SMPARTS",
                            SerialNo = "CNMRPCL5ZY",
                            Site = "SpringwoodMazdaServices"
                        },
                        new
                        {
                            Id = 65,
                            Department = "Service SM",
                            IP = "172.16.6.162",
                            Location = "SM Service R/O (David)",
                            MachineNo = "31507",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SMSRO",
                            SerialNo = "CNMRPCL743",
                            Site = "SpringwoodMazdaServices"
                        },
                        new
                        {
                            Id = 66,
                            Department = "Service SM",
                            IP = "172.16.6.163",
                            Location = "SM Service Manager (Ray)",
                            MachineNo = "31455",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SMSMAN",
                            SerialNo = "####",
                            Site = "SpringwoodMazdaServices"
                        },
                        new
                        {
                            Id = 67,
                            Department = "Service SM",
                            IP = "172.16.6.164",
                            Location = "SM Service Copier",
                            MachineNo = "31427",
                            Manufacturer = "HP",
                            Model = "E78325",
                            Name = "SMCOPIER",
                            SerialNo = "CNB1P3Q1FV",
                            Site = "SpringwoodMazdaServices"
                        },
                        new
                        {
                            Id = 68,
                            Department = "Service SM",
                            IP = "172.16.6.166",
                            Location = "SM Invoice (Nick)",
                            MachineNo = "31448",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SMSINV",
                            SerialNo = "CNMKM7P2KT",
                            Site = "SpringwoodMazdaServices"
                        },
                        new
                        {
                            Id = 69,
                            Department = "Service SM",
                            IP = "172.16.6.167",
                            Location = "SM Warranty Clerk (Caralyn)",
                            MachineNo = "31510",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "SMSWAR",
                            SerialNo = "CNMRPCL6ZH",
                            Site = "SpringwoodMazdaServices"
                        },
                        new
                        {
                            Id = 70,
                            Department = "New Cars CLMG",
                            IP = "172.16.3.144",
                            Location = "CLMG Showroom (Ethan)",
                            MachineNo = "31525",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CLMGSROOM",
                            SerialNo = "CNMRPCL78L",
                            Site = "ClevelandMG"
                        },
                        new
                        {
                            Id = 71,
                            Department = "Service CLMG",
                            IP = "172.16.3.148",
                            Location = "CLMG Service (Sarah)",
                            MachineNo = "31423",
                            Manufacturer = "HP",
                            Model = "MP2001",
                            Name = "CLMGINV",
                            SerialNo = "CNB1P3Q1DS",
                            Site = "ClevelandMG"
                        },
                        new
                        {
                            Id = 72,
                            Department = "New Cars CLMG",
                            IP = "172.16.3.152",
                            Location = "CLMG New Cars (Robert)",
                            MachineNo = "31421",
                            Manufacturer = "HP",
                            Model = "MPC2004",
                            Name = "CMGCOPIER",
                            SerialNo = "CNB1P3Q1F2",
                            Site = "ClevelandMG"
                        },
                        new
                        {
                            Id = 73,
                            Department = "New Cars CLT",
                            IP = "172.16.3.145",
                            Location = "CLT Reception (Rosina)",
                            MachineNo = "31520",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CTRECEPTION",
                            SerialNo = "CNMRPCL77C",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 74,
                            Department = "Service CLT",
                            IP = "172.16.3.149",
                            Location = "CLT Warranty (Kasey)",
                            MachineNo = "31524",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CTWAR",
                            SerialNo = "CNMRPCL5HD",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 75,
                            Department = "Finance  CLT",
                            IP = "172.16.3.151",
                            Location = "CLT Finance Office (Craig)",
                            MachineNo = "31641",
                            Manufacturer = "HP",
                            Model = "E87650",
                            Name = "CTBM1",
                            SerialNo = "CNB8K2S0LH",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 76,
                            Department = "New Cars CLT",
                            IP = "172.16.3.153",
                            Location = "CLT New Cars (Room near New Car)",
                            MachineNo = "31426",
                            Manufacturer = "HP",
                            Model = "E78325",
                            Name = "CTNCOPIER",
                            SerialNo = "CNB1P3Q1F5",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 77,
                            Department = "Service CLT",
                            IP = "172.16.3.154",
                            Location = "CLT Service (Service Advisors)",
                            MachineNo = "31428",
                            Manufacturer = "HP",
                            Model = "E78325",
                            Name = "CTSCOPIER",
                            SerialNo = "CNB1P3Q1F9",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 78,
                            Department = "New Cars CLT",
                            IP = "172.16.3.155",
                            Location = "CLT New Cars Manager (Paul)",
                            MachineNo = "31459",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "CTFLEET",
                            SerialNo = "JPBRP8F34H",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 79,
                            Department = "Used Cars Finance CLT",
                            IP = "172.16.3.157",
                            Location = "CLT Used Cars Finance (Spare)",
                            MachineNo = "31417",
                            Manufacturer = "HP",
                            Model = "E78325",
                            Name = "CTBM2",
                            SerialNo = "CNB1P3Q1FC",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 80,
                            Department = "Service CLT",
                            IP = "172.16.3.158",
                            Location = "CLT Service R/O (Workshop)",
                            MachineNo = "31522",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CTSRO",
                            SerialNo = "CNMRPCL5J2",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 81,
                            Department = "Service CLT",
                            IP = "172.16.3.161",
                            Location = "CLT Service Invoice (Service Advisors)",
                            MachineNo = "31526",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CTSINV",
                            SerialNo = "CNMRPCL5H2",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 82,
                            Department = "New Cars CLT",
                            IP = "172.16.3.162",
                            Location = "CLT New Cars (Allan)",
                            MachineNo = "31519",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CTNEW	",
                            SerialNo = "CNMRPCL5GS",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 83,
                            Department = "Parts CLT",
                            IP = "172.16.3.164",
                            Location = "CLT Parts (Front Counter)",
                            MachineNo = "31521",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CTPINV",
                            SerialNo = "CNMRPCL5FF",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 84,
                            Department = "Parts CLT",
                            IP = "172.16.3.167",
                            Location = "CLT Parts Warehouse (Warehouse)",
                            MachineNo = "31514",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "CTPWHSE",
                            SerialNo = "CNMRPCL562",
                            Site = "Cleveland"
                        },
                        new
                        {
                            Id = 85,
                            Department = "Admin RM",
                            IP = "172.16.5.152",
                            Location = "Peter Niebling Office",
                            MachineNo = "31541",
                            Manufacturer = "HP",
                            Model = "E57540",
                            Name = "RMGM",
                            SerialNo = "CNBRPCJ5D7",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 86,
                            Department = "New Car RM",
                            IP = "172.16.5.200",
                            Location = "RM New Cars (behind Reception)",
                            MachineNo = "31511",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "RMNEW",
                            SerialNo = "CNMRPCL5WC",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 87,
                            Department = "New Car RM",
                            IP = "172.16.5.201",
                            Location = "RM New Cars (beside Peter's room)",
                            MachineNo = "31642",
                            Manufacturer = "HP",
                            Model = "E87650",
                            Name = "RMRECEPTION",
                            SerialNo = "CNB8K6M0G1",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 88,
                            Department = "New Car RM",
                            IP = "172.16.5.202",
                            Location = "RM New Cars (Clare)",
                            MachineNo = "31632",
                            Manufacturer = "HP",
                            Model = "E77822",
                            Name = "RMBM1",
                            SerialNo = "CND1N6B01L",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 89,
                            Department = "New Car RM",
                            IP = "172.16.5.203",
                            Location = "RM New Cars (Alex)",
                            MachineNo = "31630",
                            Manufacturer = "HP",
                            Model = "E78330",
                            Name = "RMBM2",
                            SerialNo = "CNB1P960G3",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 90,
                            Department = "New Car RM",
                            IP = "172.16.5.204",
                            Location = "RM Aftermarket (Cathy)",
                            MachineNo = "31454",
                            Manufacturer = "HP",
                            Model = "E60155",
                            Name = "RMAFT",
                            SerialNo = "CNMKM6R9X7",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 91,
                            Department = "Service RM",
                            IP = "172.16.5.205",
                            Location = "RM Service RO (Matt Poole)",
                            MachineNo = "VM3163559306928",
                            Manufacturer = "HP",
                            Model = "P3045dn",
                            Name = "RMSRO",
                            SerialNo = "####",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 92,
                            Department = "New Car RM",
                            IP = "172.16.5.206",
                            Location = "RM Service (John)",
                            MachineNo = "31635",
                            Manufacturer = "HP",
                            Model = "E78330",
                            Name = "RMSINV",
                            SerialNo = "CNB1P960G9",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 93,
                            Department = "Parts RM",
                            IP = "172.16.5.207",
                            Location = "RM Parts (Thomas)",
                            MachineNo = "31508",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "RMPARTS",
                            SerialNo = "CNMRPCL5ZJ",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 94,
                            Department = "New Car RM",
                            IP = "172.16.5.208",
                            Location = "RM Warranty Clerk (Emma)",
                            MachineNo = "31453",
                            Manufacturer = "HP",
                            Model = "E60155",
                            Name = "RMWAR",
                            SerialNo = "CNMKM6K4PY",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 95,
                            Department = "Service RM",
                            IP = "172.16.5.209",
                            Location = "RM Service Manager (Richard)",
                            MachineNo = "31549",
                            Manufacturer = "HP",
                            Model = "E55040",
                            Name = "RMSMAN",
                            SerialNo = "JPBRP6807D",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 96,
                            Department = "New Car RM",
                            IP = "172.16.5.210",
                            Location = "RM New Car Manager (Nathan)",
                            MachineNo = "31509",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "RMNSMAN",
                            SerialNo = "CNMRPCL5Z5",
                            Site = "Brisbane"
                        },
                        new
                        {
                            Id = 97,
                            Department = "Service SWM",
                            IP = "172.16.4.142",
                            Location = "SWM Pre-Delivery Office (Helen)",
                            MachineNo = "31522",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STPDO",
                            SerialNo = "CNMRPCL54C",
                            Site = "Sydney"
                        },
                        new
                        {
                            Id = 98,
                            Department = "Parts SWT",
                            IP = "172.16.4.143",
                            Location = "PD Parts (Karen)",
                            MachineNo = "ZBR3815953",
                            Manufacturer = "Zebra",
                            Model = "ZM400",
                            Name = "####",
                            SerialNo = "####",
                            Site = "Sydney"
                        },
                        new
                        {
                            Id = 99,
                            Department = "Admin",
                            IP = "172.16.4.144",
                            Location = "PD Office - Toyota (Louise)",
                            MachineNo = "31517",
                            Manufacturer = "HP",
                            Model = "E60165",
                            Name = "STREGO",
                            SerialNo = "CNMRPCL54P",
                            Site = "Sydney"
                        },
                        new
                        {
                            Id = 100,
                            Department = "Admin",
                            IP = "172.16.4.150",
                            Location = "PD Office - Mazda (Simone)",
                            MachineNo = "VM59306911",
                            Manufacturer = "HP",
                            Model = "P3045DN",
                            Name = "SMREGO",
                            SerialNo = "####",
                            Site = "Sydney"
                        },
                        new
                        {
                            Id = 101,
                            Department = "Admin",
                            IP = "172.16.4.155",
                            Location = "PD Office",
                            MachineNo = "CNB8K831JZ",
                            Manufacturer = "HP",
                            Model = "E77830",
                            Name = "PDCOPIER",
                            SerialNo = "####",
                            Site = "Sydney"
                        },
                        new
                        {
                            Id = 102,
                            Department = "Admin",
                            IP = "172.16.4.160",
                            Location = "PD Guard House (Jackie)",
                            MachineNo = "45145PHH2P56D",
                            Manufacturer = "HP",
                            Model = "M1145",
                            Name = "PDGATE",
                            SerialNo = "####",
                            Site = "Sydney"
                        },
                        new
                        {
                            Id = 103,
                            Department = "Admin",
                            IP = "172.16.4.161",
                            Location = "PD Office (Karen)",
                            MachineNo = "45145PHH2P56B",
                            Manufacturer = "HP",
                            Model = "M1145",
                            Name = "PDPTS",
                            SerialNo = "####",
                            Site = "Sydney"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
